# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging https://hydra.cc/docs/0.11/plugins/colorlog/
defaults:
  - override job_logging: colorlog
  - override hydra_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: outputs/${model.name}/${model.kq_max_type}/${data.dataset.name}/${optimizer.optimizer_params.name}/${paths.run_name}
  
sweep:
  dir: outputs/${model.name}/${model.kq_max_type}/${data.dataset.name}/${optimizer.optimizer_params.name}/multiruns
  subdir: ${paths.run_name}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/task.log