optimizer_params:
  name: attn_rehpdhg_adamw
  lr: 0.001
  betas: [0.95, 0.95]
  weight_decay: 0
  lr_schedule: constant-linear
  warm_up_fraction: 0.4
  rho_over_lr: 1
  attn_max_iter: 1000
  momentum: false 
  attn_momentum: "none"  # "none", "prior_m", "prior_mv", "post"
  diag_scaling: false  
  enable_restart: false
  reflected_halpern: true
  warm_start: false
  pd_type: "pdhg" # "fista",  "pdhg"
