optimizer_params:
  name: attn_pd_adamw_warm_start_only
  lr: 0.001
  betas: [0.95, 0.95]
  weight_decay: 0
  lr_schedule: warm-up-cosine
  warm_up_fraction: 0.1
  rho_over_lr: 1
  attn_max_iter: 0
  lsqr_max_iter: 100
  momentum: false 
  attn_momentum: "none"  # "none", "prior_m", "prior_mv", "post"
  diag_scaling: false  
  warm_start: true
  enable_restart: false
  reflected_halpern: false
  pd_type: "pdhg" # "fista",  "pdhg"
