optimizer_params:
  name: attn_fista_adamw
  lr: 0.001
  betas: [0.95, 0.95]
  weight_decay: 0
  lr_schedule: constant-linear
  warm_up_fraction: 0.4
  max_norm_tr: 0.0001
  pdhg_max_iter: 100
  momentum: false  
  pd_type: "fista" # "fista",  "pdhg"