optimizer_params:
  name: attn_fista_adamw
  lr: 0.001
  betas: [0.95, 0.95]
  weight_decay: 0
  lr_schedule: warm-up-cosine
  warm_up_fraction: 0.1
  rho_over_lr: 1
  attn_max_iter: 100
  momentum: false
  attn_momentum: "none"  # "none", "prior_m", "prior_mv", "post"  
  warm_start: false
  mu_frac: 0.05
  pd_type: "fista" # "fista",  "pdhg"