optimizer_params:
  name: attn_rehpdhg_adamw
  lr: 0.001
  betas: [0.95, 0.95]
  weight_decay: 0
  lr_schedule: constant-linear
  warm_up_fraction: 0.4
  max_norm_tr: 0.0001
  pdhg_max_iter: 100
  momentum: false 
  diag_scaling: true 
  # acceleration: false
  enable_restart: true
  reflected_halpern: true
  warm_start: false
  pd_type: "pdhg" # "fista",  "pdhg"
