optimizer_params:
  name: attn_pdhg_adamw
  lr: 0.001
  betas: [0.95, 0.95]
  weight_decay: 0
  lr_schedule: constant-linear
  warm_up_fraction: 0.4
  max_norm_tr: 0.1
  pdhg_max_iter: 100
  pdhg_momentum: true 