optimizer_params:
  name: muon-momo
  lr: 0.01
  weight_decay: 0
  lr_schedule: constant-linear
  warm_up_fraction: 0.4
  # muon_lr: 0.01 
  muon_lr_ratio: 1.0          # allow override
  truncate_loss: 3.2

